import { Connection, PublicKey, SystemProgram, type ConfirmOptions } from '@solana/web3.js';
import { AnchorProvider, Program, setProvider, type Idl } from '@coral-xyz/anchor';
import BN from 'bn.js';
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { env } from '../config/env.js';
import { logger } from '../config/logger.js';
import { getServerKeypair } from './keypair.js';
import { AppError, ErrorCode, type TxResult, toX10 } from '@groundtruth/types';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load IDL generated by `anchor build`
const IDL_PATH = resolve(__dirname, '../../../../programs/target/idl/groundtruth.json');

function loadIdl(): Idl {
  const raw = readFileSync(IDL_PATH, 'utf-8');
  return JSON.parse(raw) as Idl;
}

let _program: Program | null = null;

function getProgram(): Program {
  if (_program) return _program;

  const keypair = getServerKeypair();
  const connection = new Connection(env.SOLANA_RPC_URL, 'confirmed');
  const wallet = {
    publicKey: keypair.publicKey,
    signTransaction: async <T extends Parameters<typeof keypair.sign>[0]>(tx: T) => {
      tx.sign(keypair);
      return tx;
    },
    signAllTransactions: async <T extends Parameters<typeof keypair.sign>[0]>(txs: T[]) => {
      txs.forEach((tx) => tx.sign(keypair));
      return txs;
    },
  };

  const opts: ConfirmOptions = { commitment: 'confirmed', maxRetries: 3 };
  const provider = new AnchorProvider(connection, wallet as Parameters<typeof AnchorProvider>[1], opts);
  setProvider(provider);

  const idl = loadIdl();
  _program = new Program(idl, provider);

  logger.info('Anchor program loaded', { programId: env.GROUNDTRUTH_PROGRAM_ID });
  return _program;
}

// ── certifyReading ────────────────────────────────────────────────────────────
// Calls certify_reading instruction on-chain and returns TX signature + PDA

export async function certifyReading(params: {
  nodeId: string;
  farmPubkey: string;
  dataHash: string; // hex string — converted to [u8; 32]
  temperatureC: number;
  humidityPct: number;
  pressureHpa: number;
  timestamp: number; // Unix ms → converted to seconds for Solana
}): Promise<TxResult> {
  const program = getProgram();
  const keypair = getServerKeypair();

  // Convert hex hash → Uint8Array[32]
  const dataHashBytes = Array.from(Buffer.from(params.dataHash, 'hex')) as number[];

  const timestampSec = Math.floor(params.timestamp / 1000);
  const farmPubkey = new PublicKey(params.farmPubkey);

  // Derive node PDA
  const [nodePda] = PublicKey.findProgramAddressSync(
    [Buffer.from('node'), Buffer.from(params.nodeId), farmPubkey.toBuffer()],
    program.programId,
  );

  // Derive cert PDA
  const timestampBuffer = Buffer.alloc(8);
  timestampBuffer.writeBigInt64LE(BigInt(timestampSec));
  const [certPda] = PublicKey.findProgramAddressSync(
    [Buffer.from('cert'), nodePda.toBuffer(), timestampBuffer],
    program.programId,
  );

  try {
    const txSignature = await (program.methods as Record<string, Function>)
      .certifyReading(
        params.nodeId,
        dataHashBytes,
        toX10(params.temperatureC),
        toX10(params.humidityPct),
        toX10(params.pressureHpa),
        new BN(timestampSec),
      )
      .accounts({
        readingCert: certPda,
        farmAccount: farmPubkey,
        nodeAccount: nodePda,
        authority: keypair.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc({ commitment: 'confirmed' }) as string;

    const cluster = env.SOLANA_RPC_URL.includes('devnet') ? 'devnet' : 'mainnet-beta';

    logger.info('Reading certified on-chain', {
      nodeId: params.nodeId,
      txSignature,
      certPda: certPda.toString(),
    });

    return {
      signature: txSignature,
      pda_address: certPda.toString(),
      explorer_url: `https://explorer.solana.com/tx/${txSignature}?cluster=${cluster}`,
      confirmed_at: new Date(),
    };
  } catch (err) {
    logger.error('Solana certify_reading failed', { err, nodeId: params.nodeId });

    const message = err instanceof Error ? err.message : 'Unknown Solana error';
    const isTimeout = message.toLowerCase().includes('timeout');

    throw new AppError(
      isTimeout ? ErrorCode.SOLANA_TIMEOUT : ErrorCode.SOLANA_TX_FAILED,
      isTimeout ? 'Solana transaction timed out' : `Solana TX failed: ${message}`,
      503,
      { nodeId: params.nodeId, err: message },
    );
  }
}
